// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycvrbmquwpujekfgtepb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljdnJibXF1d3B1amVrZmd0ZXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzIwOTUsImV4cCI6MjA3MjIwODA5NX0.692j6SRDFglfxtTq8wwVi-SvlL_iqo9o6UEkNKR3bS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});